---
title: "tidyr-101"
author: "Rodrigo"
format: html
---

```{r}
#| message: false
here::i_am("dm-course-git-101.Rproj")
library(here)
```

```{r}

#| message: false

library(ggplot2)

library(dplyr)
library(tidyr)
```


```{r}
data("EuStockMarkets")
```

```{r}
ggplot(EuStockMarkets, aes(y=DAX,x=time(EuStockMarkets))) +
  geom_line()
```

```{r}
EuStockMarkets <- 
  EuStockMarkets |>
    as_tibble() |>
    mutate(date=as.numeric(time(EuStockMarkets)))
```

```{r}
ggplot(EuStockMarkets, aes(y=DAX,x=date)) +
  geom_line()
```

```{r}
ggplot(EuStockMarkets,aes(y=CAC,x=date))+
  geom_line()
```



```{r}
ggplot(EuStockMarkets,aes(y=CAC,x=date))+
  geom_line(color="steelblue")+
  geom_line(mapping = aes(y=DAX),color="salmon")
```

### Tidyr Solution

```{r}
EuStockMarkets |>
  pivot_longer(!date, names_to="index") |>
  slice_head(n=10) |>
  knitr::kable()

```

```{r}
EuStockMarkets |>
  pivot_longer(!date, names_to="index") |>
  ggplot(aes(x=date, y=value, colour=index))+
  geom_line()
```

### More pivoting

```{r}
EuStockMarkets |>
  pivot_longer(everything())|>
   slice_head(n=10) |>
  knitr::kable()

```


```{r}
EuStockMarkets |>
  pivot_longer(DAX|SMI)|>
   slice_head(n=10) |>
  knitr::kable()
```


```{r}
EuStockMarkets |>
  select(!FTSE) |>
  pivot_longer(!date)|>summarise(avg_stock=mean(value),.by = date) |>
  slice_head(n=10) |>
  knitr::kable()
```

```{r}
EuStockMarkets|>
  select(!FTSE)|>
  rowwise() |>
  summarise(date, avg_stock=mean(DAX,SMI,CAC))
```


### Reverse op pivot to a wider format



```{r}
Eulong <- EuStockMarkets |> pivot_longer(!date)
```

```{r}
Eulong|>pivot_wider()
```


```{r}
Eulong|>pivot_wider(id_cols = date) |>
  slice_head(n=10)|>
  knitr::kable()
```



```{r}
data("diamonds")
dgroup <- diamonds|>summarise(count=n(),median_price=median(price),.by=c(cut,color))
```

```{r}
dgroup|>
  pivot_wider(id_cols = cut, names_from=color,values_from = median_price)
```
```{r}
set.seed(42)
dgroup|>
  slice_sample(n=25)|>
  pivot_wider(id_cols = cut, names_from=color,values_from = median_price)
```

# Planets star


```{r}
library(dplyr)
library(vroom)
```


```{r}

#| message: false
#| warning: false
planets <- vroom(here("P11.csv"))
stars <- vroom(here("sta11.csv"))
```


```{r}
sun_to_earth <- 333000
```
 
## innerjoin

In an inner join we keep only matches between the two data frames (according to the join_by variables)
 
```{r}


planet_star <- inner_join(planets,stars,by=join_by(Star_code))

planet_star|>
  mutate(mass_ratio=`Mass (Earth)`/sun_to_earth) |>
  slice_max(mass_ratio)|>
  select(PLANET_KEY,Planet,mass_ratio)



```

```{r}
planets_without_s <- anti_join(planets,stars,by=join_by(Star_code))
stars_without_p <- anti_join(stars,planets,by=join_by(Star_code))
```

```{r}
stars_with_p <- semi_join(stars,planets,by=join_by(Star_code))
```

```{r}
all_planets <- left_join(planets,stars,by=join_by(Star_code))
all_stars <- right_join(planets,stars,by=join_by(Star_code))
all_all <- full_join(planets,stars,by = join_by(Star_code))
```

## Star oriented analysis

```{r}
planet_star |>
  summarise(n=n(), .by=Star_code)|>
  ggplot(aes(x=n))+
    geom_bar()
```



```{r}
all_stars |>
  group_by(Star_code)|>
  count(PLANET_KEY)
```
```{r}
all_stars|>
  summarise(n=sum (!is.na(PLANET_KEY)),.by=Star_code) |>
              ggplot(aes(x=n))+
              geom_bar()
```
```{r}
all_stars|>
  summarise(n=n_distinct(PLANET_KEY),na.rm=TRUE,.by=Star_code) |>
              ggplot(aes(x=n))+
              geom_bar()
```




